### ISSUE TITLE
row for lyrics

### ISSUE THREAD

**Issue by NaanProphet** [Studio-kalavati/sargam-spec#3]
Hi there!

Would you be open to adding an additional row for specifying lyrics? Curious if that is something already on the roadmap.

**Comment by shark8me** [comment]
Hello!
I'm certainly open to accepting PRs that attempt the same. I dont plan to implement it myself at the moment.
It is relatively easy to implement a spec, but much harder to display it properly (given that the swaras and the lyrics have to be in sync vertically,

**Comment by NaanProphet** [comment]
Thanks I'll give it a shot!

I'm hoping lyrics in the Devanagari script at least would line up well, since it should map 1:1 with the `swara-labels` ("सा" "रे॒" "रे" "ग॒" "ग" "म" "म॑" "प" "ध॒" "ध" "नि॒" "नि" "-" "ऽ").

**Comment by shark8me** [comment]
Now supported in a different [project](https://github.com/Studio-kalavati/Bandish-editor), hence closing
